<script src="<?= asset('js/lib/jquery.js') ?>"></script>
<script src="<?= asset('js/lib/popper.js') ?>"></script>
<script src="<?= asset('js/lib/bootstrap.js') ?>"></script>
<script src="<?= asset('js/lib/perfect-scrollbar.js') ?>"></script>
<script src="<?= asset('js/lib/hammer.js') ?>"></script>
<script src="<?= asset('js/lib/typeahead.js') ?>"></script>
<script src="<?= asset('js/lib/menu.js') ?>"></script>
<script src="<?= asset('js/lib/moment.js') ?>"></script>
<script src="<?= asset('js/lib/datatables-bs5.js') ?>"></script>
<script src="<?= asset('js/lib/apexcharts.js') ?>"></script>
<script src="<?= asset('js/lib/main.js') ?>"></script>
<script src="<?= asset('js/lib/dashboard.js') ?>"></script>